// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gpeyczvopatbsssvaion.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdwZXljenZvcGF0YnNzc3ZhaW9uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyNzUxMTIsImV4cCI6MjA2ODg1MTExMn0.1t2OyhEqhZe54IbgMKPlR7KElNZXOmNGaF9jzf_Ocjk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce',
  },
  global: {
    headers: {
      'x-my-custom-header': 'my-app-name',
    },
  },
});