// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const APP_URL = "https://olxlunpsizvfulumdxkl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9seGx1bnBzaXp2ZnVsdW1keGtsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyNzI1OTUsImV4cCI6MjA3Mjg0ODU5NX0.3eYzqsUUYwvnM3JOMBZ588p1oavhpFyzwaHnGle25E0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(APP_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce',
  },
  global: {
    headers: {
      'x-my-custom-header': 'my-app-name',
    },
  },
});